%YAML 1.1
---
# Configuration file for vm-install

# Keys in the mappings below are virt-install(1) options, and values
# are the arguments to those options, just like you would specify on
# the virt-install(1) command line.

defaults: &defaults
  connect: qemu:///system
  memory: 8192

debian:
  <<: *defaults

rhel:
  <<: *defaults

# Local Variables:
# coding: utf-8
# End:
...
